// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	imdbws "imdb.tsv.analyzer/internal/pkg/imdbws"
)

// Imdbws is an autogenerated mock type for the Imdbws type
type Imdbws struct {
	mock.Mock
}

// GetFilmByID provides a mock function with given fields: ctx, id
func (_m *Imdbws) GetFilmByID(ctx context.Context, id string) (*imdbws.Film, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFilmByID")
	}

	var r0 *imdbws.Film
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*imdbws.Film, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *imdbws.Film); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imdbws.Film)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImdbws creates a new instance of Imdbws. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImdbws(t interface {
	mock.TestingT
	Cleanup(func())
}) *Imdbws {
	mock := &Imdbws{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
